# Generated by Django 4.0.3 on 2022-03-23 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('headline', models.CharField(default=['<django.db.models.fields.TextField>'], max_length=10)),
                ('writer', models.CharField(max_length=30)),
                ('photographer', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(default='23/03/2022 17:20:31')),
                ('date', models.DateField(default=datetime.date(2022, 3, 23))),
            ],
        ),
    ]
