# Generated by Django 4.0.3 on 2022-03-23 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_news_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 17, 27, 28, 666144)),
        ),
    ]
