# Generated by Django 4.0.3 on 2022-03-23 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_news_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 17, 28, 43, 82759)),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(default=['<django.db.models.fields.TextField>'], max_length=100),
        ),
    ]
