# Generated by Django 4.0.3 on 2022-03-23 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_news_date_time_alter_news_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 17, 31, 17, 27766)),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=100),
        ),
    ]
